global:
  name: ui-moo
  namespace: moo-system
  replicaCount: 1
container:
  image: ghcr.io/moohouse/ui-moo
  tag: latest
  pullPolicy: IfNotPresent
  secret: moo
service:
  type: ClusterIP
  port: 80
  targetPort: 10000
pdb:
  min: 2
hpa:
  min: 4
  max: 6
  cpu: 50
  ram: 50
