apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.container.name}}
  namespace: moo
  labels:
    app.kubernetes.io/instance: {{ .Values.container.name}}
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: {{ .Values.container.name}}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/instance: {{ .Values.container.name}}
      app.kubernetes.io/name: {{ .Values.container.name}}
  template:
    metadata:
      labels:
        app.kubernetes.io/instance: {{ .Values.container.name}}
        app.kubernetes.io/name: {{ .Values.container.name}}
    spec:
      imagePullSecrets:
        - name: harbor-registry-secret
      containers:
      - name : {{ .Values.container.name}}
        image: {{ .Values.container.image }}:{{ .Values.container.tag }}
        imagePullPolicy: {{ .Values.container.pullPolicy }}
        ports:
          - containerPort: {{ .Values.service.targetPort }}
            name: http
            protocol: TCP
