apiVersion: getambassador.io/v3alpha1
kind: Mapping
metadata:
  name: if-basic-auth
  namespace: default
spec:
  hostname: wall.moo.is
  prefix: /
  service: http://if-basic-auth.moo:3000
  allow_upgrade:
    - spdy/3.1
    - websocket