apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: {{ .Values.base.name }}
  namespace: {{ .Values.base.namespace }}
spec:
  replicas: {{ .Values.rollout.replicas }}
  strategy:
    canary:
      canaryService: {{ .Values.base.name }}-canary
      stableService: {{ .Values.base.name }}-stable
      trafficRouting:
        istio:
          virtualServices:
            - name: {{ .Values.config.name }}
              routes: {{ .Values.istio.vs.route }}
      steps:
        - setWeight: 10
        - pause: {}
  revisionHistoryLimit: 3
  template:
    metadata:
      labels:
        {{- if .Values.rollout.labels }}
          {{ .Values.base.labels | nindent 4 }}
        {{- end }}
        {{- if .Values.service.labels }}
          {{ .Values.service.labels | nindent 4 }}
        {{- end }}
      annotations:
        {{- if .Values.base.annotations }}
          {{ .Values.base.annotations | nindent 4 }}
        {{- end }}
        {{- if .Values.service.annotations }}
          {{ .Values.service.annotations | nindent 4 }}
        {{- end }}
    spec:
      containers:
        - name : {{ .Values.rollout.spec.containers.keycloak.name }}
          image: {{ .Values.rollout.spec.containers.keycloak.image }}
          imagePullPolicy: {{ .Values.rollout.spec.containers.keycloak.imagePullPolicy }}
          ports: {{ .Values.rollout.spec.containers.keycloak.ports }}
      {{- if .Values.rollout.spec.containers.keycloak.imagePullSecrets }}
      imagePullSecrets:
        - name : {{ .Values.rollout.spec.containers.keycloak.imagePullSecrets }}
      {{- end }}
  selector:
    matchLabels: {{ .Values.service.selector }}

