apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.base.name }}-canary
  namespace: {{ .Values.base.namespace }}
  labels:
    {{- if .Values.base.labels }}
      {{ .Values.base.labels | nindent 4 }}
    {{- end }}
    {{- if .Values.service.labels }}
      {{ .Values.service.labels | nindent 4 }}
    {{- end }}
  annotations:
    {{- if .Values.base.annotations }}
      {{ .Values.base.annotations | nindent 4 }}
    {{- end }}
    {{- if .Values.service.annotations }}
      {{ .Values.service.annotations | nindent 4 }}
    {{- end }}
spec:
  type: {{ .Values.service.type }}
  {{- if .Values.service.sessionAffinity }}
  sessionAffinity: {{ .Values.service.sessionAffinity }}
  {{- end }}
  {{- if .Values.service.sessionAffinityConfig }}
  sessionAffinityConfig: {{ .Values.service.sessionAffinityConfig | nindent 4 }}
  {{- end }}
  ports:
    - name: http
      port: {{ .Values.service.ports.http.port }}
      targetPort: {{ .Values.service.ports.http.targetPort }}
      {{- if .Values.service.ports.http.nodePort }}
      nodePort: {{ .Values.service.ports.http.nodePort }}
      {{- end }}
  selector:
    {{ .Values.base.selector }}
