apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.global.name }}
  namespace: {{ .Values.global.namespace }}
  labels:
    moo.is/name: {{ .Values.global.name }}
type: Opaque
data:
  moo: bW9vCg==

