apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.global.name }}
  namespace: {{ .Values.global.namespace }}
  labels:
    moo.is/name: {{ .Values.global.name }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: http
      port: {{ .Values.service.port }}
      protocol: TCP
      targetPort: {{ .Values.service.targetPort }}
  selector:
    moo.is/name: {{ .Values.global.name }}
  sessionAffinity: None
