base:
  name: keycloak
  namespace: town
  labels: {}
  annotations: {}
  selector:
    moo.is/name: keycloak
service:
  labels: {}
  annotations: {}
  type: ClusterIP
  ports:
    http:
      port: 8080
      targetPort: 8080
      nodePort: 30303
  sessionAffinity: ClientIP
  sessionAffinityConfig:
   clientIP:
     timeoutSeconds: 3600
rollout:
  labels: {}
  annotations: {}
  replicas: 1
  istio:
    virtualServices:
      route: keycloak.town.svc.cluster.local
  steps:
    weight: 25
    pause: {}
  revisionHistoryLimit : 1
  metadata:
    labels: {}
    annotations: {}
  spec:
    containers:
      keycloak:
        name: keycloak
        serviceAccountName: "keycloak"
        image: ghcr.io/moohouse/keycloak:9
        imagePullPolicy: IfNotPresent
        ports:
          - name: http
            containerPort: 8080
            protocol: TCP
        command:
          - "java"
        args:
          - "kc.sh"
        env:
          - name: TZ
            value: Asia/Seoul
        resources:
          requests:
            cpu: 100m
            memory: 500Mi
          limits:
            memory: 2000Mi
        imagePullSecret:



#          startupProbe:
#            httpGet:
#              path: /actuator/health/liveness
#              port: 8081
#              scheme: HTTP
#            periodSeconds: 30
#            timeoutSeconds: 10
#            successThreshold: 1
#            failureThreshold: 30
#          livenessProbe:
#            httpGet:
#              path: /actuator/health/liveness
#              port: 8081
#              scheme: HTTP
#            periodSeconds: 30
#            timeoutSeconds: 10
#            successThreshold: 1
#            failureThreshold: 10
#          readinessProbe:
#            httpGet:
#              path: /actuator/health/liveness
#              port: 8081
#              scheme: HTTP
#            periodSeconds: 30
#            timeoutSeconds: 10
#            successThreshold: 1
#            failureThreshold: 10
#
#
#          volumeMounts:
#            - mountPath: /config
#              name: spring-config
#
