apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: {{ .Values.config.name }}
  namespace: {{ .Values.config.namespace }}
  labels:
    app.kubernetes.io/name: {{ .Values.config.name }}
    app.kubernetes.io/instance: {{ .Values.config.instance }}
    app.kubernetes.io/part-of: {{ .Values.config.partof }}
    app.kubernetes.io/component: {{ .Values.config.component }}
    moo.is/name: {{ .Values.config.name }}
spec:
  hosts:  {{ .Values.istio.vs.host }}
  gateways: {{ .Values.istio.vs.gateway }}
  http:
    - name: http
      match:
        - uri:
            prefix: /
      route:
        - destination:
            host: {{ .Values.istio.vs.stable.host }}
            port:
              number: {{ .Values.istio.vs.stable.port }}
          weight: 100
        - destination:
            host: {{ .Values.istio.vs.canary.host }}
            port:
              number: {{ .Values.istio.vs.canary.port }}
          weight: 0
