name: Release Chart
on:
  push:
    branches:
      - 'main'
jobs:
  build:
    name: Publish to Github Page
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Import GPG key
        run: |
          echo "${{ secrets.GPG_PRIVATE_KEY }}" | gpg --list-secret-keys --keyid-format=long
      - name: Configure Git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"
      - name: Run chart-releaser
        uses: helm/chart-releaser-action@v1
        env:
          CR_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
          CR_KEY: "Moohead Town (Moo) <moo@moo.is>"
          CR_KEYRING: keyring.gpg
          CR_SIGN: true

